### ISSUE TITLE
[tasks_2022]: NEW App to display graphical files 10 ± 5  days or (~80 h)

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/MapR#1]
## The following are brainstorming steps that Ricardo has done:

I will deposit image files (geotiff, tiff, jpg, png, and gif) or NTCDF files at a location of my choice. A CSV file (named image_list.csv) at a fixed location will describe these image files/NTCDF (Table 1 below). I will be responsible for editing this CSV file.

![image](https://user-images.githubusercontent.com/73887426/156324507-8a3a548f-b99d-4538-b451-f27502c7c4a2.png)

The data above provides all necessary information on where files are located:

1. Directory location: URL for the file directory for each Group code
2. The directory mentioned in 1) contains sub-directories. These are named according to the entries for the field Variable.
3. Each directory mentioned in 2) contains sub-directories. These are named according to the entries for the field Measure.

For the Group codes/Group names listed above we have the following directories and sub-directories.

### Forest cover

http…. /dir1/Forest cover/Mean/
http…. /dir1/Forest cover/Error/

### World climate

http…. /dir2/Humidity/Average/
http…. /dir2/Temperature/Average/
http…. /dir2/Precipitation/Average/

### Europe temp.

http…. /dir3/Europe temp./Mean/
http…. /dir3/Europe temp./Error/

#### Vegetation cover. This is a NTCDF file as identified by the Extension field in Table 1. NTCDF files are EXCEPTIONS, In these cases, there is only one file placed in a directory named according to Group name. The corresponding file is always named 1.ntcdf

http…. /dir4/Asia climate/

The image files within the folder are ALWAYS named as an integer number (starting at 1) followed by the extension given in the Extension field (as mentioned previously only one file when this is a ntcdf file).

If a Measure sub-directory contains more than one file then the images there contained are part of a time series. The temporal values for this time series are given in a CSV file named list.CSV and having a structure as described in Table 2.

Examples:

For the group “Forest cover” and Variable “Forest cover” the Measure sub-directories contain one file each and these are tiff files:

http…. /dir1/Forest cover/Mean/1.tiff
http…. /dir1/Forest cover/Error/1.tiff

While the group World climate, Variable Temperature, and Measure Average contains 10 files:

http…. /dir2/Temperature/Average/1.tiff
http…. /dir2/Temperature/Average/2.tiff
http…. /dir2/Temperature/Average/3.tiff
http…. /dir2/Temperature/Average/4.tiff
http…. /dir2/Temperature/Average/5.tiff
http…. /dir2/Temperature/Average/6.tiff
http…. /dir2/Temperature/Average/7.tiff
http…. /dir2/Temperature/Average/8.tiff
http…. /dir2/Temperature/Average/9.tiff
http…. /dir2/Temperature/Average/10.tiff

The CSV file measure.CSV lists all of these files and gives their temporal value (Table 2 below)

Table 2 File (measure.CSV) listing image files within a Measure sub-directory

![image](https://user-images.githubusercontent.com/73887426/156326797-89c760a0-76da-4b6a-88f6-d6fa22807d92.png)

# HOW DOES THE DISPLAY WORK?

1. The user can select between single map display or with time plot display. We start with the example of Single Map display shown below

![image](https://user-images.githubusercontent.com/73887426/156327014-8e8f29c4-f904-4fd3-a73e-9870e9861331.png)

2. In pending list 1 user selects a Group name as shown in Table 1 (only shown once as per Group code) (e.g. World climate)
3. The choice made in 1 populates Pending list 2. Here are shown the option in Variable (Table 1) for selected Group (e.g. Temperature)
4. The choice made in 2 populates Pending list 3. Here are shown the options in Measure (Table 1) for selected Variable (e.g. Average)
5. The choice made in 3 populates Pending list 4. A check is made if the Measure sub-directory contains a measure.CSV file. If not, no additional option is given in Pending list 4. If it does contain the file. Then the options are given in the column Time of Table 2.
6. The user can then press “Display” to show the selected map. (NOTE: for NTCDF files we will provide code to display the image). In the example above 2001 was selected. The title is optional and can be edited by the user. By default it should be the concatenation of “Variable” + “Measure” + “(Unit)” as per Table 1.
7. Not shown in above are options to add/hide points (size/color/text label options). User can also can which ranges to display. Add titles to x and y axes (options for font type/size/colour). Show/hid/modify title (text/ font type/size/colour). User can also export images in different formats (tiff, png, jpg, pdf).

![image](https://user-images.githubusercontent.com/73887426/156327305-fcc2cf27-48a5-43f8-895f-3ec65cd5dcce.png)

8. The other main option is that the user can instead select Time plot to extract corresponding data (figure above). This only works if a Measure sub-directory contains multiple files as per Table 2. The x-axis for the time series will have values along a scale defined by time in Table 2. 
9. The user selects a Measure as in points 2 to 4 above. 
10. The user selects a latitude and longitude if a NTCDF file (R code to be provided) or x-pixel and y-pixel values if a raster. This will extract values along the multiple rasters for that location. It will populate Table 2 the value of interest. Example for temperature:

![image](https://user-images.githubusercontent.com/73887426/156327477-13481bc1-af5b-48fb-8e88-608adfd50798.png)

11. By having Time and a y-value as in the Table above we can then use PlotR code to create a smoothed temporal plot. When the user presses “Extract data” then a  CSV file is created containing columns 2 and 3 from above. The user can save this and then load it into PlotR

## ALTERNATIVE 1

As an alternative to point 11 one could do directly the plot within the app if it is possible to use the code from PlotR. In this case, it would be possible to add multiple plots but only the option to show these overlapping would be made available. MCMC/smoothing options still include plus adding points to graph. 

## ALTERNATIVE 2

The data generated in point 11 is fed directly into PlotR

**Comment by f-lukas** [comment]
@isomemo. Is it possible that you already provide us with sample files so that I can test the creation of the maps? In the first step, one sample file per file format (tiff, jpeg, NTCDF) would be helpful. Afterwards it would be optimal to have a sample file for each combination of unit and measure (e.g. Density_Mean, Density_Error, Celsius_Mean , Celsius_Error, ...). With this I can test that different units and measures are displayed appropriately.
It is not necessary that the files are already stored in the correct directory structure (unless this is already the case or easy to implement). Otherwise, I can first create an exemplary directory structure based on the example in https://github.com/Pandora-IsoMemo/MapR/issues/1#issue-1156813840 and then transfer it later to the final directory structure.

**Comment by isomemo** [comment]
@f-lukas @arunge I will create some image files but for the NTCDF format I need to put you in touch with my colleagues at Cambridge. They can give you faster feedback on any queries you may have. Do you have an email that I share with them?

**Comment by arunge** [comment]
@isomemo You told me that there is a package regarding the NTCDF files that was just released. Is it the `ncdf4` package?
- https://cran.r-project.org/web/packages/ncdf4/index.html
- https://pjbartlein.github.io/REarthSysSci/netCDF.html
- https://rpubs.com/boyerag/297592

**Comment by isomemo** [comment]
@arunge yes, this package: https://cran.r-project.org/web/packages/pastclim/index.html

I think that it would make the job simpler. See instructions here: https://github.com/EvolEcolGroup/pastclim
https://evolecolgroup.github.io/pastclim/articles/a0_pastclim_overview.html

Before any implementation, we should discuss how the use of NTCDF files is described in the JSON file. Until now I have only sent instructions for raster images.

**Comment by arunge** [comment]
The integration of the import module from `DataTools` will need some slight modification of the module itself. The structure of zip-objects of `MapR` is very different to the structure of all the other apps zip-objects. I will extract the respective logic into a function, such that the specific logic for `MapR` can live in a separate function in the package `MapR`.

**Comment by isomemo** [comment]
@arunge please close this!

**Comment by arunge** [comment]
New/left features will be discussed in separate issues, e.g. see
- https://github.com/Pandora-IsoMemo/MapR/issues/13

I am closing here.
