### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/MapR#4]
@arunge what is the status of MapR? According to GitHub this was last worked on 4 months ago.

**Comment by arunge** [comment]
In the meanwhile, we have all to continue here.
However, I prioritized other tasks to be finished first, e.g. updates regarding the API for the iso-app. But if you would like to continue here with the left budget than we can also do so. 

@isomemo What do you prefer?

**Comment by isomemo** [comment]
@arunge Is there anything I can test on MapR?

**Comment by arunge** [comment]
@isomemo The app cannot be tested yet. With 
>  we have all to continue here.

I meant that @f-lukas has all example data and could continue with developing the app. He is just waiting for my go to continue here. However, as mentioned [above](https://github.com/Pandora-IsoMemo/MapR/issues/4#issuecomment-1557010723), I prioritized different tasks to be done first. Should he continue here, with this task, instead that we finish changes regarding the API instead?

**Comment by isomemo** [comment]
@arunge s that's a pity because by comparing the status of both I could better make a decision. What exactly is missing concerning the API?

**Comment by arunge** [comment]
@isomemo The updates regarding the API are online now:
- https://github.com/Pandora-IsoMemo/iso-app/issues/102#issuecomment-1593335309

However, in order to continue with MapR, we must wait for the new task list.
