### ISSUE TITLE
Integrate NTCF files

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/MapR#5]
- [ ] To handle the display of maps/temporal plots for NTCF files, use this package: https://cran.r-project.org/web/packages/pastclim/index.html

**Comment by f-lukas** [comment]
The display of NTCDF files is implemented in the current beta version of the app. @isomemo could you please test whether the display works as expected (https://pandoraapp.earth/app/mapr-beta)? Please note that only the display of the map is implemented and the temporal plot will be added in the next step. Thank you!
